- name: Install and run Nginx
  hosts: mongodb
  become: yes
  #list
  tasks:
  - name: Install nginxXX
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: Start nginxXXX
    ansible.builtin.service:
      name: nginx
      state: started