- name: variables in ansible
  hosts: mongodb
  vars:
    course: DevOps
    Trainer: Siva
    Student: Sudheer
    Duration: 130Hrs
  tasks:
  - name: Printing text in output
    ansible.builtin.debug:
      msg: "Hello world, I am learning DevOps"